/** 
 * Resume.java
 */
package sample;
import java.awt.*;
import java.awt.event.*;

public class Resume extends Frame implements ItemListener {

    /** Initializes the applet Resume */
    public static void main (String[] args) {
        final Resume res = new Resume();
        res.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent evt) {
                res.setVisible(false);
                res.dispose();
                System.exit(0);
            }
        });
        res.setLayoutManager();
        res.initComponents ();
        res.pack();
        res.setVisible(true);
    }
    
    public void setLayoutManager() {
        setLayout(new FlowLayout());
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        choice2 = new java.awt.Choice();
        choice2.add("Objective");
        choice2.add("Qualification");
        choice2.add("Experience");
        choice2.add("Skillset");
        choice2.add("Education");
        choice2.add("Training");
        choice2.addItemListener(this);
        choice2.select(0);
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        textArea2 = new java.awt.TextArea();
        panel3 = new java.awt.Panel();
        textArea1 = new java.awt.TextArea();
        panel4 = new java.awt.Panel();
        textArea3 = new java.awt.TextArea();
        panel5 = new java.awt.Panel();
        textArea4 = new java.awt.TextArea();
        panel6 = new java.awt.Panel();
        textArea5 = new java.awt.TextArea();
        panel7 = new java.awt.Panel();
        textArea6 = new java.awt.TextArea();
        
        choice2.setFont(new java.awt.Font ("Dialog", 0, 11));
        choice2.setName("choice2");
        choice2.setBackground(java.awt.Color.white);
        choice2.setForeground(java.awt.Color.black);
        
        add(choice2);
        
        
        panel1.setLayout(new java.awt.CardLayout());
        panel1.setFont(new java.awt.Font ("Dialog", 0, 11));
        panel1.setName("panel20");
        panel1.setBackground(new java.awt.Color (204, 204, 204));
        panel1.setForeground(java.awt.Color.black);
        
        panel2.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel2.setName("panel21");
          panel2.setBackground(new java.awt.Color (153, 153, 153));
          panel2.setForeground(java.awt.Color.black);
          
          textArea2.setBackground(new java.awt.Color (216, 208, 200));
            textArea2.setName("text4");
            textArea2.setEditable(false);
            textArea2.setFont(new java.awt.Font ("Courier New", 0, 12));
            textArea2.setColumns(80);
            textArea2.setForeground(new java.awt.Color (0, 0, 204));
            textArea2.setText("Seeking a challenging position as a JAVA Programmer.\n");
            textArea2.setRows(20);
            panel2.add(textArea2);
            
            panel1.add(panel2, "Objective");
          
          
        panel3.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel3.setName("panel22");
          panel3.setBackground(new java.awt.Color (153, 153, 153));
          panel3.setForeground(java.awt.Color.black);
          
          textArea1.setBackground(new java.awt.Color (216, 208, 200));
            textArea1.setName("text3");
            textArea1.setEditable(false);
            textArea1.setFont(new java.awt.Font ("Courier New", 1, 12));
            textArea1.setColumns(80);
            textArea1.setForeground(java.awt.Color.black);
            textArea1.setText("* 7 years C/C++ experience, UNIX/Windows\n*  7 years experience in RDBMS, including Oracle, Informix and Sybase\n* 3 years programming experience in JAVA on UNIX/WINDOWS\n* 2 years experience in designing and developing in J2EE\n* ");
            textArea1.setRows(20);
            panel3.add(textArea1);
            
            panel1.add(panel3, "Qualification");
          
          
        panel4.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel4.setName("panel23");
          panel4.setBackground(new java.awt.Color (153, 153, 153));
          panel4.setForeground(java.awt.Color.black);
          
          textArea3.setBackground(new java.awt.Color (216, 208, 200));
            textArea3.setName("text5");
            textArea3.setEditable(false);
            textArea3.setFont(new java.awt.Font ("Courier New", 0, 12));
            textArea3.setColumns(80);
            textArea3.setForeground(java.awt.Color.blue);
            textArea3.setText("Technical Support / Systems Engineer\nSun Microsystems Inc. China Ltd.  PRC \n");
            textArea3.setRows(20);
            panel4.add(textArea3);
            
            panel1.add(panel4, "Experience");
          
          
        panel5.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel5.setName("panel24");
          panel5.setBackground(new java.awt.Color (153, 153, 153));
          panel5.setForeground(java.awt.Color.black);
          
          textArea4.setBackground(new java.awt.Color (216, 208, 200));
            textArea4.setName("text6");
            textArea4.setEditable(false);
            textArea4.setFont(new java.awt.Font ("Courier New", 0, 12));
            textArea4.setColumns(80);
            textArea4.setForeground(java.awt.Color.blue);
            textArea4.setText("Programming: C++, JAVA, XML \n");
            textArea4.setRows(20);
            panel5.add(textArea4);
            
            panel1.add(panel5, "Skillset");
          
          
        panel6.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel6.setName("panel25");
          panel6.setBackground(new java.awt.Color (153, 153, 153));
          panel6.setForeground(java.awt.Color.black);
          
          textArea5.setBackground(new java.awt.Color (216, 208, 200));
            textArea5.setName("text7");
            textArea5.setEditable(false);
            textArea5.setFont(new java.awt.Font ("Courier New", 0, 12));
            textArea5.setColumns(80);
            textArea5.setForeground(java.awt.Color.blue);
            textArea5.setText("University of Science and Technology of China");
            textArea5.setRows(20);
            panel6.add(textArea5);
            
            panel1.add(panel6, "Education");
          
          
        panel7.setFont(new java.awt.Font ("Dialog", 0, 11));
          panel7.setName("panel26");
          panel7.setBackground(new java.awt.Color (153, 153, 153));
          panel7.setForeground(java.awt.Color.black);
          
          textArea6.setBackground(new java.awt.Color (216, 208, 200));
            textArea6.setName("text8");
            textArea6.setEditable(false);
            textArea6.setFont(new java.awt.Font ("Courier New", 0, 12));
            textArea6.setColumns(80);
            textArea6.setForeground(java.awt.Color.blue);
            textArea6.setText("Sun Microsystems Inc.   1998-2001\nAttended training course \n");
            textArea6.setRows(20);
            panel7.add(textArea6);
            
            panel1.add(panel7, "Training");
          
          
        add(panel1);
        
    }//GEN-END:initComponents

    public void itemStateChanged(ItemEvent evt) {
        CardLayout card = (CardLayout)panel1.getLayout();
        card.show(panel1, (String)evt.getItem());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.TextArea textArea2;
    private java.awt.Panel panel3;
    private java.awt.TextArea textArea1;
    private java.awt.Panel panel4;
    private java.awt.TextArea textArea3;
    private java.awt.Panel panel5;
    private java.awt.TextArea textArea4;
    private java.awt.Panel panel6;
    private java.awt.TextArea textArea5;
    private java.awt.Panel panel7;
    private java.awt.TextArea textArea6;
    // End of variables declaration//GEN-END:variables

}
